### ISSUE TITLE
Primera revision cuentas de usuario

### ISSUE THREAD

**Issue by Charlie8810** [innovafourdimension/Doitclick#1]
Buscar detalles de la app que sean globales y solucionarlos

- [x] El nombre y correo del usuario debe ser dinámico 
- [x] Se debe poder cerrar sesión 
- [ ] Se debe poder actualizar contraseña
- [ ] Puedo colocar mi foto de perfil
- [x] Mostrar mensaje de error cuando mi contraseña o usuario esta mal

**Comment by capradenas** [comment]
**Primera revision cuentas de usuario**

*El nombre y correo del usuario debe ser dinámico 
*Se debe poder cerrar sesión 
*Se debe poder actualizar contraseña
*Puedo colocar mi foto de perfil

**Comment by Charlie8810** [comment]
Se terminaran las otras dos tareas pendientes mas adelante por temas de prioridades.

**Comment by Charlie8810** [comment]
Se cierra por vieja
