### ISSUE TITLE
Solicitudes de material mensual

### ISSUE THREAD

**Issue by Charlie8810** [innovafourdimension/Doitclick#2]
Se debe generar una pantalla para solicitar materiales que son de uso mensual y otra para aprobar y/o rechazar las solicitudes de estos.

Estos materiales se deben descontar del stock asi que tambien se debe **generar una pantalla para ingresar estos materiales** y se pueda ingresar nuevo stock.

para esto se necesita las siguientes entidades:

*Material Mensual*
Id
Nombre
Cantidad
Descripción
Precio

*Solicitud Material*
Id
Fecha Inicio
Comentarios
Estado [Pendiente, Aprobado, Rechazado, Entregado]
Fecha Finalizacion
Comentario Finalizacion

*Material Solicitado*
IdMaterial
IdSolicitud
cantidadMateriales

Todo
- [x] Pantalla de solicitud de materiales
- [x] Pantalla de listado de solicitudes de solicitante y resolutor
- [x] Pantalla de Revision de solicitud de estos
- [x] Pantalla para agregar nuevo stock

**Comment by cmunoz780** [comment]
pantalla de solicitud de material mensual en proceso

**Comment by Charlie8810** [comment]
@cmunoz780 póngale fecha de fin a esto

**Comment by cmunoz780** [comment]
estoy preparando la maquoina!!!!

**Comment by Charlie8810** [comment]
@innovafourdimension/doitclick-dev  @capradenas  se encargara de esta funcionalidad, ahora @cmunoz780 esta revisando las validaciones

**Comment by Charlie8810** [comment]
Todo resuelto en la pull request #13

**Comment by Charlie8810** [comment]
para que el solicitante pueda abrir una nueva solicitud debe tener cerrada las ultimas 3 que abrió.

**Comment by Charlie8810** [comment]
A la cuarta solicitud este no permite generarla hasta que se cierre uno y abra el cupo
