### ISSUE TITLE
Mantenedores no guardan al editar

### ISSUE THREAD

**Issue by Charlie8810** [innovafourdimension/Doitclick#3]
**Mantenedores no guardan al editar** 
- [x] Hacer un catastro de cuantos son
- [x] Corregir todo lo que se encuentre anomalo

**Nuevo**
- [ ] Mantenedor de Servicios no puede quitar materiales
- [ ] Revisar los reportes de Ximena ya que no están funcionando varias cosas en los mantenedores

**Comment by Charlie8810** [comment]
Ximena indico que el mantenedor de usuario no edita bien un usuario creado

**Comment by Charlie8810** [comment]
Se revisaron todos los mantenedores y se les corrigió cada anomalía encontrada, con respecto a lo que mencionó Ximena ya se corrigió también.

**Comment by Charlie8810** [comment]
Los mantenedores aun no están estables, revisar, enumerar y corregir.

**Comment by cmunoz780** [comment]
1.  Mantenedor Marcas 
- [x]  Nuevo, mensaje de guardar
- [x] Editar, se blanquea, pero direccionamiento al listado
- [x] Eliminar, 5 Segundos, en refrescar e ir al listado

2. Mantenedor Unidad Medida hace todo, pero se deben modificar los combobox
- [x]  Nuevo, mensaje de guardar
- [ ] Editar, se blanquea, pero direccionamiento al listado
- [ ] Eliminar, 5 Segundos, en refrescar e ir al listado

3. Matenedor Materiales // se dejan asi 

- [x]  Nuevo, mensaje de guardar
- [ ] Editar, se blanquea, pero direccionamiento al listado
- [ ] Eliminar, 5 Segundos, en refrescar e ir al listado

4. Matenedor Instrumento

- [x]  Nuevo, mensaje de guardar
- [x] Editar, se blanquea, pero direccionamiento al listado
- [x] Eliminar, 5 Segundos, en refrescar e ir al listado

5. Mantenedor Cliente,
- [x] Nuevo, guarda
- [ ] Editar, problemas  <input type="text" value="@(ViewBag.editando ? ViewBag.cliente.EntidadFacturacion.Rut : "")" id="rut-facturacion" class="form-control">
![image](https://user-images.githubusercontent.com/13221005/61196639-0b87bf00-a69e-11e9-874a-7ebc03d19092.png)
