### ISSUE TITLE
Revisión de todos los mantenedores

### ISSUE THREAD

**Issue by Charlie8810** [innovafourdimension/Doitclick#8]
Revisión y corrección de mantenedores 
Mantenedores a Revisar y corregir:
- [x] Marcas
- [x] Unidades de Medida
- [x] Materiales
- [x] Material Mensual
- [x] Instrumentos
- [x] Trabajos / Servicios
- [x] Organizaciones
- [x] Roles
- [x] Usuarios

**Comment by cmunoz780** [comment]
Validaciones de guardado y formato :

- [x] Marcas
- [x] Unidades de Medida
- [x] Materiales
- [ ] Material Mensual   --> no esta abriendo el mantenedor
- [x] Instrumento
- [ ] Trabajos/Servicios
- [ ] Cliente (Cliente hay que re-hacerlo completo)
- [ ] Organizaciones
- [ ] Roles
- [ ] Usuarios

**Comment by Charlie8810** [comment]
Material Mensual
@cmunoz780 mira en la vista Formulario.cshtml de material mensual 

![image](https://user-images.githubusercontent.com/8751718/47604338-bea86f00-d9ce-11e8-88de-00323e6631a4.png)
El codigo marcado con rojo es el malo borralo y bprueba denuevo

**Comment by Charlie8810** [comment]
Todos los mantenedores revisados y corregidos
